domain                     = "cairn.ing"
dynamodb_table_arn         = "arn:aws:dynamodb:us-east-2:405988826931:table/cairn-dev"
dynamodb_table_name        = "cairn-dev"
environment                = "dev"
hosted_zone_id             = "Z02456308PQX2QC1QSJH"
ses_configuration_set_name = "cairn-dev"
ses_from_email             = "noreply@cairn.ing"
