module "github_oidc" {
  source                  = "../../modules/github_oidc"
  environment             = var.environment
  github_repo             = "levi-smith17/cairn-summit"
  managed_by              = var.managed_by
  owner                   = var.owner
  project_name            = var.project_name
  terraform_state_bucket  = "cairn-dev-terraform-state"

  dynamodb_table_arn = module.dynamodb.table_arn
  lambda_function_arns = [
    module.lambda_burn_create.function_arn,
    module.lambda_burn_delete.function_arn,
    module.lambda_burn_get.function_arn,
    module.lambda_burn_update.function_arn,
    module.lambda_cache_carry_over.function_arn,
    module.lambda_cache_create.function_arn,
    module.lambda_cache_delete.function_arn,
    module.lambda_cache_get.function_arn,
    module.lambda_cache_update.function_arn,
    module.lambda_guides_create.function_arn,
    module.lambda_guides_delete.function_arn,
    module.lambda_guides_get.function_arn,
    module.lambda_guides_placements_reset.function_arn,
    module.lambda_guides_stones_create.function_arn,
    module.lambda_guides_stones_get.function_arn,
    module.lambda_guides_stones_import.function_arn,
    module.lambda_guides_update.function_arn,
    module.lambda_itinerary_create.function_arn,
    module.lambda_itinerary_delete.function_arn,
    module.lambda_itinerary_update.function_arn,
    module.lambda_itinerary_subscriptions_create.function_arn,
    module.lambda_itinerary_subscriptions_delete.function_arn,
    module.lambda_itinerary_subscriptions_update.function_arn,
    module.lambda_logs_create.function_arn,
    module.lambda_logs_delete.function_arn,
    module.lambda_logs_get.function_arn,
    module.lambda_logs_update.function_arn,
    module.lambda_manifest_companions_create.function_arn,
    module.lambda_manifest_companions_delete.function_arn,
    module.lambda_manifest_companions_update.function_arn,
    module.lambda_manifest_expeditions_create.function_arn,
    module.lambda_manifest_expeditions_delete.function_arn,
    module.lambda_manifest_expeditions_update.function_arn,
    module.lambda_manifest_gear_create.function_arn,
    module.lambda_manifest_gear_delete.function_arn,
    module.lambda_manifest_gear_update.function_arn,
    module.lambda_manifest_get.function_arn,
    module.lambda_manifest_landmarks_create.function_arn,
    module.lambda_manifest_landmarks_delete.function_arn,
    module.lambda_manifest_landmarks_update.function_arn,
    module.lambda_manifest_origins_update.function_arn,
    module.lambda_manifest_pathfinding_create.function_arn,
    module.lambda_manifest_pathfinding_delete.function_arn,
    module.lambda_manifest_pathfinding_update.function_arn,
    module.lambda_manifest_settings_update.function_arn,
    module.lambda_manifest_summits_create.function_arn,
    module.lambda_manifest_summits_delete.function_arn,
    module.lambda_manifest_summits_update.function_arn,
    module.lambda_manifest_training_create.function_arn,
    module.lambda_manifest_training_delete.function_arn,
    module.lambda_manifest_training_update.function_arn,
    module.lambda_markers_create.function_arn,
    module.lambda_markers_delete.function_arn,
    module.lambda_markers_get.function_arn,
    module.lambda_markers_update.function_arn,
    module.lambda_profile_get.function_arn,
    module.lambda_settings_delete_account.function_arn,
    module.lambda_settings_get.function_arn,
    module.lambda_settings_update.function_arn,
    module.lambda_signals_contact.function_arn,
    module.lambda_signals_delete.function_arn,
    module.lambda_signals_get.function_arn,
    module.lambda_signals_mark_read.function_arn,
    module.lambda_signals_public_thread_get.function_arn,
    module.lambda_signals_public_thread_reply.function_arn,
    module.lambda_signals_reply.function_arn,
    module.lambda_signals_sync.function_arn,
    module.lambda_stones_delete.function_arn,
    module.lambda_stones_placement_update.function_arn,
    module.lambda_stones_update.function_arn,
    module.lambda_supplylines_create.function_arn,
    module.lambda_supplylines_delete.function_arn,
    module.lambda_supplylines_get.function_arn,
    module.lambda_supplylines_summary.function_arn,
    module.lambda_supplylines_update.function_arn,
    module.lambda_trails_create.function_arn,
    module.lambda_trails_delete.function_arn,
    module.lambda_trails_get.function_arn,
    module.lambda_trails_update.function_arn,
    module.lambda_waypoints_create.function_arn,
    module.lambda_waypoints_delete.function_arn,
    module.lambda_waypoints_get.function_arn,
    module.lambda_waypoints_update.function_arn,
  ]
}