domain                     = "cairn.ing"
dynamodb_table_arn         = "arn:aws:dynamodb:us-east-2:491121232780:table/cairn-prod"
dynamodb_table_name        = "cairn-prod"
environment                = "prod"
hosted_zone_id             = "Z02456308PQX2QC1QSJH"
ses_configuration_set_name = "cairn-prod"
ses_from_email             = "noreply@cairn.ing"