#!/bin/bash
set -e

if [ -z "$1" ]; then
  echo "Usage: ./state_mv.sh <aws-profile>"
  exit 1
fi

export AWS_PROFILE="$1"

terraform state mv 'module.lambda_basecamp_get' 'module.lambdas.module.lambda["basecamp-get"]'
terraform state mv 'module.lambda_basecamp_sidebar' 'module.lambdas.module.lambda["basecamp-sidebar"]'
terraform state mv 'module.lambda_basecamp_trail_waypoints' 'module.lambdas.module.lambda["basecamp-trail-waypoints"]'

terraform state mv 'module.lambda_burn_create' 'module.lambdas.module.lambda["burn-create"]'
terraform state mv 'module.lambda_burn_delete' 'module.lambdas.module.lambda["burn-delete"]'
terraform state mv 'module.lambda_burn_get' 'module.lambdas.module.lambda["burn-get"]'
terraform state mv 'module.lambda_burn_receipt_delete' 'module.lambdas.module.lambda["burn-receipt-delete"]'
terraform state mv 'module.lambda_burn_receipt_upload_url' 'module.lambdas.module.lambda["burn-receipt-upload-url"]'
terraform state mv 'module.lambda_burn_receipt_url' 'module.lambdas.module.lambda["burn-receipt-url"]'
terraform state mv 'module.lambda_burn_update' 'module.lambdas.module.lambda["burn-update"]'

terraform state mv 'module.lambda_cache_carry_over' 'module.lambdas.module.lambda["cache-carry-over"]'
terraform state mv 'module.lambda_cache_create' 'module.lambdas.module.lambda["cache-create"]'
terraform state mv 'module.lambda_cache_delete' 'module.lambdas.module.lambda["cache-delete"]'
terraform state mv 'module.lambda_cache_get' 'module.lambdas.module.lambda["cache-get"]'
terraform state mv 'module.lambda_cache_update' 'module.lambdas.module.lambda["cache-update"]'

terraform state mv 'module.lambda_guides_create' 'module.lambdas.module.lambda["guides-create"]'
terraform state mv 'module.lambda_guides_delete' 'module.lambdas.module.lambda["guides-delete"]'
terraform state mv 'module.lambda_guides_get' 'module.lambdas.module.lambda["guides-get"]'
terraform state mv 'module.lambda_guides_placements_reset' 'module.lambdas.module.lambda["guides-placements-reset"]'
terraform state mv 'module.lambda_guides_stones_create' 'module.lambdas.module.lambda["guides-stones-create"]'
terraform state mv 'module.lambda_guides_stones_get' 'module.lambdas.module.lambda["guides-stones-get"]'
terraform state mv 'module.lambda_guides_stones_import' 'module.lambdas.module.lambda["guides-stones-import"]'
terraform state mv 'module.lambda_guides_update' 'module.lambdas.module.lambda["guides-update"]'
terraform state mv 'module.lambda_stones_delete' 'module.lambdas.module.lambda["guides-stones-delete"]'
terraform state mv 'module.lambda_stones_placement_update' 'module.lambdas.module.lambda["guides-stones-placement-update"]'
terraform state mv 'module.lambda_stones_update' 'module.lambdas.module.lambda["guides-stones-update"]'

terraform state mv 'module.lambda_headwaters_kin_create' 'module.lambdas.module.lambda["headwaters-kin-create"]'
terraform state mv 'module.lambda_headwaters_kin_delete' 'module.lambdas.module.lambda["headwaters-kin-delete"]'
terraform state mv 'module.lambda_headwaters_kin_get' 'module.lambdas.module.lambda["headwaters-kin-get"]'
terraform state mv 'module.lambda_headwaters_kin_update' 'module.lambdas.module.lambda["headwaters-kin-update"]'

terraform state mv 'module.lambda_itinerary_calendars_create' 'module.lambdas.module.lambda["itinerary-calendars-create"]'
terraform state mv 'module.lambda_itinerary_calendars_delete' 'module.lambdas.module.lambda["itinerary-calendars-delete"]'
terraform state mv 'module.lambda_itinerary_calendars_update' 'module.lambdas.module.lambda["itinerary-calendars-update"]'
terraform state mv 'module.lambda_itinerary_subscriptions_create' 'module.lambdas.module.lambda["itinerary-subscriptions-create"]'
terraform state mv 'module.lambda_itinerary_subscriptions_delete' 'module.lambdas.module.lambda["itinerary-subscriptions-delete"]'
terraform state mv 'module.lambda_itinerary_subscriptions_update' 'module.lambdas.module.lambda["itinerary-subscriptions-update"]'

terraform state mv 'module.lambda_logs_create' 'module.lambdas.module.lambda["logs-create"]'
terraform state mv 'module.lambda_logs_delete' 'module.lambdas.module.lambda["logs-delete"]'
terraform state mv 'module.lambda_logs_get' 'module.lambdas.module.lambda["logs-get"]'
terraform state mv 'module.lambda_logs_update' 'module.lambdas.module.lambda["logs-update"]'
terraform state mv 'module.lambda_logs_upload_url' 'module.lambdas.module.lambda["logs-upload-url"]'

terraform state mv 'module.lambda_manifest_companions_create' 'module.lambdas.module.lambda["manifest-companions-create"]'
terraform state mv 'module.lambda_manifest_companions_delete' 'module.lambdas.module.lambda["manifest-companions-delete"]'
terraform state mv 'module.lambda_manifest_companions_media_delete' 'module.lambdas.module.lambda["manifest-companions-media-delete"]'
terraform state mv 'module.lambda_manifest_companions_media_upload' 'module.lambdas.module.lambda["manifest-companions-media-upload"]'
terraform state mv 'module.lambda_manifest_companions_update' 'module.lambdas.module.lambda["manifest-companions-update"]'
terraform state mv 'module.lambda_manifest_expeditions_create' 'module.lambdas.module.lambda["manifest-expeditions-create"]'
terraform state mv 'module.lambda_manifest_expeditions_delete' 'module.lambdas.module.lambda["manifest-expeditions-delete"]'
terraform state mv 'module.lambda_manifest_expeditions_update' 'module.lambdas.module.lambda["manifest-expeditions-update"]'
terraform state mv 'module.lambda_manifest_gear_create' 'module.lambdas.module.lambda["manifest-gear-create"]'
terraform state mv 'module.lambda_manifest_gear_delete' 'module.lambdas.module.lambda["manifest-gear-delete"]'
terraform state mv 'module.lambda_manifest_gear_update' 'module.lambdas.module.lambda["manifest-gear-update"]'
terraform state mv 'module.lambda_manifest_get' 'module.lambdas.module.lambda["manifest-get"]'
terraform state mv 'module.lambda_manifest_landmarks_create' 'module.lambdas.module.lambda["manifest-landmarks-create"]'
terraform state mv 'module.lambda_manifest_landmarks_delete' 'module.lambdas.module.lambda["manifest-landmarks-delete"]'
terraform state mv 'module.lambda_manifest_landmarks_update' 'module.lambdas.module.lambda["manifest-landmarks-update"]'
terraform state mv 'module.lambda_manifest_origins_update' 'module.lambdas.module.lambda["manifest-origins-update"]'
terraform state mv 'module.lambda_manifest_pathfinding_create' 'module.lambdas.module.lambda["manifest-pathfinding-create"]'
terraform state mv 'module.lambda_manifest_pathfinding_delete' 'module.lambdas.module.lambda["manifest-pathfinding-delete"]'
terraform state mv 'module.lambda_manifest_pathfinding_update' 'module.lambdas.module.lambda["manifest-pathfinding-update"]'
terraform state mv 'module.lambda_manifest_settings_update' 'module.lambdas.module.lambda["manifest-settings-update"]'
terraform state mv 'module.lambda_manifest_summits_create' 'module.lambdas.module.lambda["manifest-summits-create"]'
terraform state mv 'module.lambda_manifest_summits_delete' 'module.lambdas.module.lambda["manifest-summits-delete"]'
terraform state mv 'module.lambda_manifest_summits_update' 'module.lambdas.module.lambda["manifest-summits-update"]'
terraform state mv 'module.lambda_manifest_training_create' 'module.lambdas.module.lambda["manifest-training-create"]'
terraform state mv 'module.lambda_manifest_training_delete' 'module.lambdas.module.lambda["manifest-training-delete"]'
terraform state mv 'module.lambda_manifest_training_update' 'module.lambdas.module.lambda["manifest-training-update"]'

terraform state mv 'module.lambda_markers_create' 'module.lambdas.module.lambda["markers-create"]'
terraform state mv 'module.lambda_markers_delete' 'module.lambdas.module.lambda["markers-delete"]'
terraform state mv 'module.lambda_markers_get' 'module.lambdas.module.lambda["markers-get"]'
terraform state mv 'module.lambda_markers_update' 'module.lambdas.module.lambda["markers-update"]'

terraform state mv 'module.lambda_profile_get' 'module.lambdas.module.lambda["profile-get"]'

terraform state mv 'module.lambda_settings_delete_account' 'module.lambdas.module.lambda["settings-delete-account"]'
terraform state mv 'module.lambda_settings_get' 'module.lambdas.module.lambda["settings-get"]'
terraform state mv 'module.lambda_settings_update' 'module.lambdas.module.lambda["settings-update"]'

terraform state mv 'module.lambda_signals_contact' 'module.lambdas.module.lambda["signals-contact"]'
terraform state mv 'module.lambda_signals_delete' 'module.lambdas.module.lambda["signals-delete"]'
terraform state mv 'module.lambda_signals_get' 'module.lambdas.module.lambda["signals-get"]'
terraform state mv 'module.lambda_signals_mark_read' 'module.lambdas.module.lambda["signals-mark-read"]'
terraform state mv 'module.lambda_signals_public_thread_get' 'module.lambdas.module.lambda["signals-public-thread-get"]'
terraform state mv 'module.lambda_signals_public_thread_reply' 'module.lambdas.module.lambda["signals-public-thread-reply"]'
terraform state mv 'module.lambda_signals_reply' 'module.lambdas.module.lambda["signals-reply"]'
terraform state mv 'module.lambda_signals_sync' 'module.lambdas.module.lambda["signals-sync"]'

terraform state mv 'module.lambda_starfield_network_create' 'module.lambdas.module.lambda["starfield-network-create"]'
terraform state mv 'module.lambda_starfield_network_delete' 'module.lambdas.module.lambda["starfield-network-delete"]'
terraform state mv 'module.lambda_starfield_network_update' 'module.lambdas.module.lambda["starfield-network-update"]'
terraform state mv 'module.lambda_starfield_networks_get' 'module.lambdas.module.lambda["starfield-networks-get"]'
terraform state mv 'module.lambda_starfield_outpost_create' 'module.lambdas.module.lambda["starfield-outpost-create"]'
terraform state mv 'module.lambda_starfield_outpost_delete' 'module.lambdas.module.lambda["starfield-outpost-delete"]'
terraform state mv 'module.lambda_starfield_outpost_position' 'module.lambdas.module.lambda["starfield-outpost-position"]'
terraform state mv 'module.lambda_starfield_outpost_resource_delete' 'module.lambdas.module.lambda["starfield-outpost-resource-delete"]'
terraform state mv 'module.lambda_starfield_outpost_resource_upsert' 'module.lambdas.module.lambda["starfield-outpost-resource-upsert"]'
terraform state mv 'module.lambda_starfield_outpost_update' 'module.lambdas.module.lambda["starfield-outpost-update"]'
terraform state mv 'module.lambda_starfield_outposts_get' 'module.lambdas.module.lambda["starfield-outposts-get"]'
terraform state mv 'module.lambda_starfield_resource_create' 'module.lambdas.module.lambda["starfield-resource-create"]'
terraform state mv 'module.lambda_starfield_resource_delete' 'module.lambdas.module.lambda["starfield-resource-delete"]'
terraform state mv 'module.lambda_starfield_resource_update' 'module.lambdas.module.lambda["starfield-resource-update"]'
terraform state mv 'module.lambda_starfield_resources_get' 'module.lambdas.module.lambda["starfield-resources-get"]'
terraform state mv 'module.lambda_starfield_system_create' 'module.lambdas.module.lambda["starfield-system-create"]'
terraform state mv 'module.lambda_starfield_system_delete' 'module.lambdas.module.lambda["starfield-system-delete"]'
terraform state mv 'module.lambda_starfield_system_planet_create' 'module.lambdas.module.lambda["starfield-system-planet-create"]'
terraform state mv 'module.lambda_starfield_system_planet_delete' 'module.lambdas.module.lambda["starfield-system-planet-delete"]'
terraform state mv 'module.lambda_starfield_system_planet_update' 'module.lambdas.module.lambda["starfield-system-planet-update"]'
terraform state mv 'module.lambda_starfield_system_update' 'module.lambdas.module.lambda["starfield-system-update"]'
terraform state mv 'module.lambda_starfield_systems_get' 'module.lambdas.module.lambda["starfield-systems-get"]'

terraform state mv 'module.lambda_supplylines_create' 'module.lambdas.module.lambda["supplylines-create"]'
terraform state mv 'module.lambda_supplylines_delete' 'module.lambdas.module.lambda["supplylines-delete"]'
terraform state mv 'module.lambda_supplylines_get' 'module.lambdas.module.lambda["supplylines-get"]'
terraform state mv 'module.lambda_supplylines_summary' 'module.lambdas.module.lambda["supplylines-summary"]'
terraform state mv 'module.lambda_supplylines_update' 'module.lambdas.module.lambda["supplylines-update"]'

terraform state mv 'module.lambda_trails_create' 'module.lambdas.module.lambda["trails-create"]'
terraform state mv 'module.lambda_trails_delete' 'module.lambdas.module.lambda["trails-delete"]'
terraform state mv 'module.lambda_trails_get' 'module.lambdas.module.lambda["trails-get"]'
terraform state mv 'module.lambda_trails_update' 'module.lambdas.module.lambda["trails-update"]'

terraform state mv 'module.lambda_waypoints_create' 'module.lambdas.module.lambda["waypoints-create"]'
terraform state mv 'module.lambda_waypoints_delete' 'module.lambdas.module.lambda["waypoints-delete"]'
terraform state mv 'module.lambda_waypoints_fetch_meta' 'module.lambdas.module.lambda["waypoints-fetch-meta"]'
terraform state mv 'module.lambda_waypoints_get' 'module.lambdas.module.lambda["waypoints-get"]'
terraform state mv 'module.lambda_waypoints_update' 'module.lambdas.module.lambda["waypoints-update"]'

echo "State migration complete."
