import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('Seeding Starfield data...')

  // Resource Types
  const resourceTypeMap: Record<number, string> = {}
  { const rt = await prisma.sfResourceType.upsert({ where: { name: "gas" }, update: {}, create: { name: "gas", plural: "es" } }); resourceTypeMap[1] = rt.id }
  { const rt = await prisma.sfResourceType.upsert({ where: { name: "solid" }, update: {}, create: { name: "solid", plural: "s" } }); resourceTypeMap[2] = rt.id }
  { const rt = await prisma.sfResourceType.upsert({ where: { name: "liquid" }, update: {}, create: { name: "liquid", plural: "s" } }); resourceTypeMap[3] = rt.id }
  { const rt = await prisma.sfResourceType.upsert({ where: { name: "manufactured" }, update: {}, create: { name: "manufactured", plural: "" } }); resourceTypeMap[4] = rt.id }

  // Resources
  const resourceMap: Record<number, string> = {}
  { const r = await prisma.sfResource.upsert({ where: { name: "Adhesive" }, update: {}, create: { name: "Adhesive", abbreviation: "ADV", typeId: resourceTypeMap[2] } }); resourceMap[1] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Aldumite" }, update: {}, create: { name: "Aldumite", abbreviation: "Ad", typeId: resourceTypeMap[2] } }); resourceMap[2] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Alkanes" }, update: {}, create: { name: "Alkanes", abbreviation: "HnCn", typeId: resourceTypeMap[1] } }); resourceMap[3] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Aluminum" }, update: {}, create: { name: "Aluminum", abbreviation: "Al", typeId: resourceTypeMap[2] } }); resourceMap[4] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Amino Acids" }, update: {}, create: { name: "Amino Acids", abbreviation: "AAC", typeId: resourceTypeMap[2] } }); resourceMap[5] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Analgesic" }, update: {}, create: { name: "Analgesic", abbreviation: "AGC", typeId: resourceTypeMap[2] } }); resourceMap[6] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Antimicrobial" }, update: {}, create: { name: "Antimicrobial", abbreviation: "ANT", typeId: resourceTypeMap[2] } }); resourceMap[7] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Antimony" }, update: {}, create: { name: "Antimony", abbreviation: "Sb", typeId: resourceTypeMap[2] } }); resourceMap[8] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Argon" }, update: {}, create: { name: "Argon", abbreviation: "Ar", typeId: resourceTypeMap[1] } }); resourceMap[9] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Aromatic" }, update: {}, create: { name: "Aromatic", abbreviation: "ARO", typeId: resourceTypeMap[2] } }); resourceMap[10] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Benzene" }, update: {}, create: { name: "Benzene", abbreviation: "C6Hn", typeId: resourceTypeMap[1] } }); resourceMap[11] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Beryllium" }, update: {}, create: { name: "Beryllium", abbreviation: "Be", typeId: resourceTypeMap[2] } }); resourceMap[12] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Biosuppressant" }, update: {}, create: { name: "Biosuppressant", abbreviation: "BIO", typeId: resourceTypeMap[3] } }); resourceMap[13] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Caesium" }, update: {}, create: { name: "Caesium", abbreviation: "Cs", typeId: resourceTypeMap[3] } }); resourceMap[14] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Carboxylic Acids" }, update: {}, create: { name: "Carboxylic Acids", abbreviation: "R-COOH", typeId: resourceTypeMap[3] } }); resourceMap[15] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Chlorine" }, update: {}, create: { name: "Chlorine", abbreviation: "Cl", typeId: resourceTypeMap[1] } }); resourceMap[16] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Chlorosilanes" }, update: {}, create: { name: "Chlorosilanes", abbreviation: "SiH3Cl", typeId: resourceTypeMap[3] } }); resourceMap[17] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Cobalt" }, update: {}, create: { name: "Cobalt", abbreviation: "Co", typeId: resourceTypeMap[2] } }); resourceMap[18] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Copper" }, update: {}, create: { name: "Copper", abbreviation: "Cu", typeId: resourceTypeMap[2] } }); resourceMap[19] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Cosmetic" }, update: {}, create: { name: "Cosmetic", abbreviation: "COS", typeId: resourceTypeMap[2] } }); resourceMap[20] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Dysprosium" }, update: {}, create: { name: "Dysprosium", abbreviation: "Dy", typeId: resourceTypeMap[2] } }); resourceMap[21] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Europium" }, update: {}, create: { name: "Europium", abbreviation: "Eu", typeId: resourceTypeMap[2] } }); resourceMap[22] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Fiber" }, update: {}, create: { name: "Fiber", abbreviation: "FIB", typeId: resourceTypeMap[2] } }); resourceMap[23] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Fluorine" }, update: {}, create: { name: "Fluorine", abbreviation: "F", typeId: resourceTypeMap[1] } }); resourceMap[24] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Gastronomic Delight" }, update: {}, create: { name: "Gastronomic Delight", abbreviation: "GDT", typeId: resourceTypeMap[2] } }); resourceMap[25] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Gold" }, update: {}, create: { name: "Gold", abbreviation: "Au", typeId: resourceTypeMap[2] } }); resourceMap[26] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Hallucinogen" }, update: {}, create: { name: "Hallucinogen", abbreviation: "HAL", typeId: resourceTypeMap[2] } }); resourceMap[27] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Helium-3" }, update: {}, create: { name: "Helium-3", abbreviation: "He3", typeId: resourceTypeMap[1] } }); resourceMap[28] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "High-Tensile Spidroin" }, update: {}, create: { name: "High-Tensile Spidroin", abbreviation: "HTS", typeId: resourceTypeMap[2] } }); resourceMap[29] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Hypercatalyst" }, update: {}, create: { name: "Hypercatalyst", abbreviation: "HYP", typeId: resourceTypeMap[2] } }); resourceMap[30] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Immunostimulant" }, update: {}, create: { name: "Immunostimulant", abbreviation: "IMS", typeId: resourceTypeMap[2] } }); resourceMap[31] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Indicite" }, update: {}, create: { name: "Indicite", abbreviation: "IE", typeId: resourceTypeMap[2] } }); resourceMap[32] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Ionic Liquids" }, update: {}, create: { name: "Ionic Liquids", abbreviation: "IL", typeId: resourceTypeMap[3] } }); resourceMap[33] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Iridium" }, update: {}, create: { name: "Iridium", abbreviation: "Ir", typeId: resourceTypeMap[2] } }); resourceMap[34] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Iron" }, update: {}, create: { name: "Iron", abbreviation: "Fe", typeId: resourceTypeMap[2] } }); resourceMap[35] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Lead" }, update: {}, create: { name: "Lead", abbreviation: "Pb", typeId: resourceTypeMap[2] } }); resourceMap[36] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Lithium" }, update: {}, create: { name: "Lithium", abbreviation: "Li", typeId: resourceTypeMap[2] } }); resourceMap[37] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Lubricant" }, update: {}, create: { name: "Lubricant", abbreviation: "LUB", typeId: resourceTypeMap[2] } }); resourceMap[38] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Luxury Textile" }, update: {}, create: { name: "Luxury Textile", abbreviation: "LTX", typeId: resourceTypeMap[2] } }); resourceMap[39] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Membrane" }, update: {}, create: { name: "Membrane", abbreviation: "MEB", typeId: resourceTypeMap[2] } }); resourceMap[40] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Memory Substrate" }, update: {}, create: { name: "Memory Substrate", abbreviation: "MEM", typeId: resourceTypeMap[2] } }); resourceMap[41] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Mercury" }, update: {}, create: { name: "Mercury", abbreviation: "Hg", typeId: resourceTypeMap[3] } }); resourceMap[42] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Metabolic Agent" }, update: {}, create: { name: "Metabolic Agent", abbreviation: "MAT", typeId: resourceTypeMap[2] } }); resourceMap[43] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Neodymium" }, update: {}, create: { name: "Neodymium", abbreviation: "Nd", typeId: resourceTypeMap[2] } }); resourceMap[44] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Neon" }, update: {}, create: { name: "Neon", abbreviation: "Ne", typeId: resourceTypeMap[1] } }); resourceMap[45] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Neurologic" }, update: {}, create: { name: "Neurologic", abbreviation: "NEU", typeId: resourceTypeMap[2] } }); resourceMap[46] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Nickel" }, update: {}, create: { name: "Nickel", abbreviation: "Ni", typeId: resourceTypeMap[2] } }); resourceMap[47] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Nutrient" }, update: {}, create: { name: "Nutrient", abbreviation: "NUT", typeId: resourceTypeMap[2] } }); resourceMap[48] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Ornamental Material" }, update: {}, create: { name: "Ornamental Material", abbreviation: "OMA", typeId: resourceTypeMap[2] } }); resourceMap[49] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Palladium" }, update: {}, create: { name: "Palladium", abbreviation: "Pd", typeId: resourceTypeMap[2] } }); resourceMap[50] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Pigment" }, update: {}, create: { name: "Pigment", abbreviation: "PIG", typeId: resourceTypeMap[2] } }); resourceMap[51] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Platinum" }, update: {}, create: { name: "Platinum", abbreviation: "Pt", typeId: resourceTypeMap[2] } }); resourceMap[52] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Plutonium" }, update: {}, create: { name: "Plutonium", abbreviation: "Pu", typeId: resourceTypeMap[2] } }); resourceMap[53] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Polymer" }, update: {}, create: { name: "Polymer", abbreviation: "PLY", typeId: resourceTypeMap[2] } }); resourceMap[54] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Rothicite" }, update: {}, create: { name: "Rothicite", abbreviation: "Rc", typeId: resourceTypeMap[2] } }); resourceMap[55] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Sealant" }, update: {}, create: { name: "Sealant", abbreviation: "SEA", typeId: resourceTypeMap[2] } }); resourceMap[56] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Sedative" }, update: {}, create: { name: "Sedative", abbreviation: "SED", typeId: resourceTypeMap[2] } }); resourceMap[57] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Silver" }, update: {}, create: { name: "Silver", abbreviation: "Ag", typeId: resourceTypeMap[2] } }); resourceMap[58] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Solvent" }, update: {}, create: { name: "Solvent", abbreviation: "SOL", typeId: resourceTypeMap[2] } }); resourceMap[59] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Spice" }, update: {}, create: { name: "Spice", abbreviation: "SPC", typeId: resourceTypeMap[2] } }); resourceMap[60] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Stimulant" }, update: {}, create: { name: "Stimulant", abbreviation: "STM", typeId: resourceTypeMap[2] } }); resourceMap[61] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Structural Material" }, update: {}, create: { name: "Structural Material", abbreviation: "SMA", typeId: resourceTypeMap[2] } }); resourceMap[62] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Tantalum" }, update: {}, create: { name: "Tantalum", abbreviation: "Ta", typeId: resourceTypeMap[2] } }); resourceMap[63] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Tasine" }, update: {}, create: { name: "Tasine", abbreviation: "Tsn", typeId: resourceTypeMap[3] } }); resourceMap[64] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Tetrafluorides" }, update: {}, create: { name: "Tetrafluorides", abbreviation: "xF4", typeId: resourceTypeMap[1] } }); resourceMap[65] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Titanium" }, update: {}, create: { name: "Titanium", abbreviation: "Ti", typeId: resourceTypeMap[2] } }); resourceMap[66] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Toxin" }, update: {}, create: { name: "Toxin", abbreviation: "TOX", typeId: resourceTypeMap[2] } }); resourceMap[67] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Tungsten" }, update: {}, create: { name: "Tungsten", abbreviation: "W", typeId: resourceTypeMap[2] } }); resourceMap[68] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Uranium" }, update: {}, create: { name: "Uranium", abbreviation: "U", typeId: resourceTypeMap[2] } }); resourceMap[69] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Vanadium" }, update: {}, create: { name: "Vanadium", abbreviation: "V", typeId: resourceTypeMap[2] } }); resourceMap[70] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Veryl" }, update: {}, create: { name: "Veryl", abbreviation: "Vr", typeId: resourceTypeMap[1] } }); resourceMap[71] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Vytinium" }, update: {}, create: { name: "Vytinium", abbreviation: "Vy", typeId: resourceTypeMap[2] } }); resourceMap[72] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Water" }, update: {}, create: { name: "Water", abbreviation: "H20", typeId: resourceTypeMap[3] } }); resourceMap[73] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Xenon" }, update: {}, create: { name: "Xenon", abbreviation: "Xe", typeId: resourceTypeMap[1] } }); resourceMap[74] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Ytterbium" }, update: {}, create: { name: "Ytterbium", abbreviation: "Yb", typeId: resourceTypeMap[2] } }); resourceMap[75] = r.id }

  // Manufactured Resources
  { const r = await prisma.sfResource.upsert({ where: { name: "Zero Wire" }, update: {}, create: { name: "Zero Wire", abbreviation: "ZERO", typeId: resourceTypeMap[4], resource1Id: resourceMap[19], resource2Id: resourceMap[58] } }); resourceMap[77] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Isocentered Magnet" }, update: {}, create: { name: "Isocentered Magnet", abbreviation: "ICMT", typeId: resourceTypeMap[4], resource1Id: resourceMap[18], resource2Id: resourceMap[47] } }); resourceMap[78] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Adaptive Frame" }, update: {}, create: { name: "Adaptive Frame", abbreviation: "ADFM", typeId: resourceTypeMap[4], resource1Id: resourceMap[4], resource2Id: resourceMap[35] } }); resourceMap[79] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Isotopic Coolant" }, update: {}, create: { name: "Isotopic Coolant", abbreviation: "ISOC", typeId: resourceTypeMap[4], resource1Id: resourceMap[33], resource2Id: resourceMap[65] } }); resourceMap[80] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Positron Battery" }, update: {}, create: { name: "Positron Battery", abbreviation: "PBAT", typeId: resourceTypeMap[4], resource1Id: resourceMap[83], resource2Id: resourceMap[8], resource3Id: resourceMap[70] } }); resourceMap[82] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Tau Grade Rheostat" }, update: {}, create: { name: "Tau Grade Rheostat", abbreviation: "TGRT", typeId: resourceTypeMap[4], resource1Id: resourceMap[19], resource2Id: resourceMap[12] } }); resourceMap[83] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Paramagnon Conductor" }, update: {}, create: { name: "Paramagnon Conductor", abbreviation: "PAMC", typeId: resourceTypeMap[4], resource1Id: resourceMap[26], resource2Id: resourceMap[44], resource3Id: resourceMap[77] } }); resourceMap[84] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Supercooled Magnet" }, update: {}, create: { name: "Supercooled Magnet", abbreviation: "SMAG", typeId: resourceTypeMap[4], resource1Id: resourceMap[78], resource2Id: resourceMap[80], resource3Id: resourceMap[44] } }); resourceMap[85] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Microsecond Regulator" }, update: {}, create: { name: "Microsecond Regulator", abbreviation: "MREG", typeId: resourceTypeMap[4], resource1Id: resourceMap[83], resource2Id: resourceMap[37], resource3Id: resourceMap[22], resource4Id: resourceMap[85] } }); resourceMap[86] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Austenitic Manifold" }, update: {}, create: { name: "Austenitic Manifold", abbreviation: "AFOL", typeId: resourceTypeMap[4], resource1Id: resourceMap[47], resource2Id: resourceMap[88], resource3Id: resourceMap[35] } }); resourceMap[87] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Reactive Gauge" }, update: {}, create: { name: "Reactive Gauge", abbreviation: "RGAU", typeId: resourceTypeMap[4], resource1Id: resourceMap[19], resource2Id: resourceMap[4] } }); resourceMap[88] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Comm Relay" }, update: {}, create: { name: "Comm Relay", abbreviation: "COMM", typeId: resourceTypeMap[4], resource1Id: resourceMap[83], resource2Id: resourceMap[78] } }); resourceMap[89] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Mag Pressure Tank" }, update: {}, create: { name: "Mag Pressure Tank", abbreviation: "MGPT", typeId: resourceTypeMap[4], resource1Id: resourceMap[47], resource2Id: resourceMap[4] } }); resourceMap[90] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Monopropellant" }, update: {}, create: { name: "Monopropellant", abbreviation: "MPRO", typeId: resourceTypeMap[4], resource1Id: resourceMap[90], resource2Id: resourceMap[3], resource3Id: resourceMap[88] } }); resourceMap[91] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Semimetal Wafer" }, update: {}, create: { name: "Semimetal Wafer", abbreviation: "SWFR", typeId: resourceTypeMap[4], resource1Id: resourceMap[26], resource2Id: resourceMap[8], resource3Id: resourceMap[77] } }); resourceMap[92] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Indicite Wafer" }, update: {}, create: { name: "Indicite Wafer", abbreviation: "IWFR", typeId: resourceTypeMap[4], resource1Id: resourceMap[32], resource2Id: resourceMap[14], resource3Id: resourceMap[92], resource4Id: resourceMap[59] } }); resourceMap[93] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Nuclear Fuel Rod" }, update: {}, create: { name: "Nuclear Fuel Rod", abbreviation: "NFRD", typeId: resourceTypeMap[4], resource1Id: resourceMap[92], resource2Id: resourceMap[69], resource3Id: resourceMap[59] } }); resourceMap[94] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Control Rod" }, update: {}, create: { name: "Control Rod", abbreviation: "CTRL", typeId: resourceTypeMap[4], resource1Id: resourceMap[87], resource2Id: resourceMap[21], resource3Id: resourceMap[80] } }); resourceMap[95] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Rothicite Magnet" }, update: {}, create: { name: "Rothicite Magnet", abbreviation: "RMAG", typeId: resourceTypeMap[4], resource1Id: resourceMap[37], resource2Id: resourceMap[92], resource3Id: resourceMap[55], resource4Id: resourceMap[85] } }); resourceMap[96] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Power Circuit" }, update: {}, create: { name: "Power Circuit", abbreviation: "PCRT", typeId: resourceTypeMap[4], resource1Id: resourceMap[84], resource2Id: resourceMap[54], resource3Id: resourceMap[50], resource4Id: resourceMap[82] } }); resourceMap[97] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Tasine Superconductor" }, update: {}, create: { name: "Tasine Superconductor", abbreviation: "TSNS", typeId: resourceTypeMap[4], resource1Id: resourceMap[84], resource2Id: resourceMap[54], resource3Id: resourceMap[64], resource4Id: resourceMap[50] } }); resourceMap[98] = r.id }
  { const r = await prisma.sfResource.upsert({ where: { name: "Vytinium Fuel Rod" }, update: {}, create: { name: "Vytinium Fuel Rod", abbreviation: "VROD", typeId: resourceTypeMap[4], resource1Id: resourceMap[93], resource2Id: resourceMap[53], resource3Id: resourceMap[94], resource4Id: resourceMap[72] } }); resourceMap[99] = r.id }

  // Systems
  const systemMap: Record<number, string> = {}
  { const s = await prisma.sfSystem.upsert({ where: { name: "Maheo" }, update: {}, create: { name: "Maheo" } }); systemMap[1] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Cheyenne" }, update: {}, create: { name: "Cheyenne" } }); systemMap[2] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Nikola" }, update: {}, create: { name: "Nikola" } }); systemMap[3] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Huygens" }, update: {}, create: { name: "Huygens" } }); systemMap[4] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Bohr" }, update: {}, create: { name: "Bohr" } }); systemMap[5] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Rana" }, update: {}, create: { name: "Rana" } }); systemMap[6] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Fermi" }, update: {}, create: { name: "Fermi" } }); systemMap[7] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Schrodinger" }, update: {}, create: { name: "Schrodinger" } }); systemMap[8] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Carinae" }, update: {}, create: { name: "Carinae" } }); systemMap[9] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Alpha Andraste" }, update: {}, create: { name: "Alpha Andraste" } }); systemMap[10] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Eridani" }, update: {}, create: { name: "Eridani" } }); systemMap[11] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Hyla" }, update: {}, create: { name: "Hyla" } }); systemMap[12] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Decaran" }, update: {}, create: { name: "Decaran" } }); systemMap[13] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Alpha Tirna" }, update: {}, create: { name: "Alpha Tirna" } }); systemMap[14] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Archimedes" }, update: {}, create: { name: "Archimedes" } }); systemMap[15] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Zelazny" }, update: {}, create: { name: "Zelazny" } }); systemMap[16] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Katydid" }, update: {}, create: { name: "Katydid" } }); systemMap[17] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Zeta Ophiuchi" }, update: {}, create: { name: "Zeta Ophiuchi" } }); systemMap[18] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Verne" }, update: {}, create: { name: "Verne" } }); systemMap[19] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Sparta" }, update: {}, create: { name: "Sparta" } }); systemMap[20] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Shoza" }, update: {}, create: { name: "Shoza" } }); systemMap[21] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Ixyll" }, update: {}, create: { name: "Ixyll" } }); systemMap[22] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Narion" }, update: {}, create: { name: "Narion" } }); systemMap[23] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Nirah" }, update: {}, create: { name: "Nirah" } }); systemMap[24] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Maal" }, update: {}, create: { name: "Maal" } }); systemMap[25] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Strix" }, update: {}, create: { name: "Strix" } }); systemMap[26] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Moloch" }, update: {}, create: { name: "Moloch" } }); systemMap[27] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Kang" }, update: {}, create: { name: "Kang" } }); systemMap[28] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Masada" }, update: {}, create: { name: "Masada" } }); systemMap[29] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Bel" }, update: {}, create: { name: "Bel" } }); systemMap[30] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Muphrid" }, update: {}, create: { name: "Muphrid" } }); systemMap[31] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Kavnyk" }, update: {}, create: { name: "Kavnyk" } }); systemMap[32] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Gamma Vulpes" }, update: {}, create: { name: "Gamma Vulpes" } }); systemMap[34] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Jaffa" }, update: {}, create: { name: "Jaffa" } }); systemMap[35] = s.id }
  { const s = await prisma.sfSystem.upsert({ where: { name: "Al-Battani" }, update: {}, create: { name: "Al-Battani" } }); systemMap[36] = s.id }

  // Planets
  const planetMap: Record<number, string> = {}
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Maheo I", systemId: systemMap[1] } }, update: {}, create: { name: "Maheo I", systemId: systemMap[1] } }); planetMap[1] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Maheo II", systemId: systemMap[1] } }, update: {}, create: { name: "Maheo II", systemId: systemMap[1] } }); planetMap[2] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Maheo III", systemId: systemMap[1] } }, update: {}, create: { name: "Maheo III", systemId: systemMap[1] } }); planetMap[3] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Maheo III-a", systemId: systemMap[1] } }, update: {}, create: { name: "Maheo III-a", systemId: systemMap[1] } }); planetMap[4] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Maheo III-b", systemId: systemMap[1] } }, update: {}, create: { name: "Maheo III-b", systemId: systemMap[1] } }); planetMap[5] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Maheo IV", systemId: systemMap[1] } }, update: {}, create: { name: "Maheo IV", systemId: systemMap[1] } }); planetMap[6] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Maheo IV-a", systemId: systemMap[1] } }, update: {}, create: { name: "Maheo IV-a", systemId: systemMap[1] } }); planetMap[7] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Maheo IV-b", systemId: systemMap[1] } }, update: {}, create: { name: "Maheo IV-b", systemId: systemMap[1] } }); planetMap[8] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Maheo IV-c", systemId: systemMap[1] } }, update: {}, create: { name: "Maheo IV-c", systemId: systemMap[1] } }); planetMap[9] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Maheo IV-d", systemId: systemMap[1] } }, update: {}, create: { name: "Maheo IV-d", systemId: systemMap[1] } }); planetMap[10] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Maheo V", systemId: systemMap[1] } }, update: {}, create: { name: "Maheo V", systemId: systemMap[1] } }); planetMap[11] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Maheo V-a", systemId: systemMap[1] } }, update: {}, create: { name: "Maheo V-a", systemId: systemMap[1] } }); planetMap[12] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Maheo VI", systemId: systemMap[1] } }, update: {}, create: { name: "Maheo VI", systemId: systemMap[1] } }); planetMap[13] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Maheo VI-a", systemId: systemMap[1] } }, update: {}, create: { name: "Maheo VI-a", systemId: systemMap[1] } }); planetMap[14] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Maheo VII", systemId: systemMap[1] } }, update: {}, create: { name: "Maheo VII", systemId: systemMap[1] } }); planetMap[15] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Maheo VII-a", systemId: systemMap[1] } }, update: {}, create: { name: "Maheo VII-a", systemId: systemMap[1] } }); planetMap[16] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Rana I", systemId: systemMap[6] } }, update: {}, create: { name: "Rana I", systemId: systemMap[6] } }); planetMap[17] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Rana I-a", systemId: systemMap[6] } }, update: {}, create: { name: "Rana I-a", systemId: systemMap[6] } }); planetMap[18] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Rana I-b", systemId: systemMap[6] } }, update: {}, create: { name: "Rana I-b", systemId: systemMap[6] } }); planetMap[19] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Rana I-c", systemId: systemMap[6] } }, update: {}, create: { name: "Rana I-c", systemId: systemMap[6] } }); planetMap[20] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Rana II", systemId: systemMap[6] } }, update: {}, create: { name: "Rana II", systemId: systemMap[6] } }); planetMap[21] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Rana II-a", systemId: systemMap[6] } }, update: {}, create: { name: "Rana II-a", systemId: systemMap[6] } }); planetMap[22] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Rana III", systemId: systemMap[6] } }, update: {}, create: { name: "Rana III", systemId: systemMap[6] } }); planetMap[23] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Rana III-a", systemId: systemMap[6] } }, update: {}, create: { name: "Rana III-a", systemId: systemMap[6] } }); planetMap[24] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Rana IV", systemId: systemMap[6] } }, update: {}, create: { name: "Rana IV", systemId: systemMap[6] } }); planetMap[25] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Rana V", systemId: systemMap[6] } }, update: {}, create: { name: "Rana V", systemId: systemMap[6] } }); planetMap[26] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Rana V-a", systemId: systemMap[6] } }, update: {}, create: { name: "Rana V-a", systemId: systemMap[6] } }); planetMap[27] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Rana VI", systemId: systemMap[6] } }, update: {}, create: { name: "Rana VI", systemId: systemMap[6] } }); planetMap[28] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Rana VI-a", systemId: systemMap[6] } }, update: {}, create: { name: "Rana VI-a", systemId: systemMap[6] } }); planetMap[29] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Rana VI-b", systemId: systemMap[6] } }, update: {}, create: { name: "Rana VI-b", systemId: systemMap[6] } }); planetMap[30] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Rana VI-c", systemId: systemMap[6] } }, update: {}, create: { name: "Rana VI-c", systemId: systemMap[6] } }); planetMap[31] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Rana VI-d", systemId: systemMap[6] } }, update: {}, create: { name: "Rana VI-d", systemId: systemMap[6] } }); planetMap[32] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Rana VI-e", systemId: systemMap[6] } }, update: {}, create: { name: "Rana VI-e", systemId: systemMap[6] } }); planetMap[33] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Rana VII", systemId: systemMap[6] } }, update: {}, create: { name: "Rana VII", systemId: systemMap[6] } }); planetMap[34] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Rana VII-a", systemId: systemMap[6] } }, update: {}, create: { name: "Rana VII-a", systemId: systemMap[6] } }); planetMap[35] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Rana VII-b", systemId: systemMap[6] } }, update: {}, create: { name: "Rana VII-b", systemId: systemMap[6] } }); planetMap[36] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Rana VIII", systemId: systemMap[6] } }, update: {}, create: { name: "Rana VIII", systemId: systemMap[6] } }); planetMap[37] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Rana IX", systemId: systemMap[6] } }, update: {}, create: { name: "Rana IX", systemId: systemMap[6] } }); planetMap[38] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Rana IX-a", systemId: systemMap[6] } }, update: {}, create: { name: "Rana IX-a", systemId: systemMap[6] } }); planetMap[39] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Rana IX-b", systemId: systemMap[6] } }, update: {}, create: { name: "Rana IX-b", systemId: systemMap[6] } }); planetMap[40] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Maal I", systemId: systemMap[25] } }, update: {}, create: { name: "Maal I", systemId: systemMap[25] } }); planetMap[41] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Maal II", systemId: systemMap[25] } }, update: {}, create: { name: "Maal II", systemId: systemMap[25] } }); planetMap[42] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Alpha Andraste III", systemId: systemMap[10] } }, update: {}, create: { name: "Alpha Andraste III", systemId: systemMap[10] } }); planetMap[46] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Alpha Tirna VIII-c", systemId: systemMap[14] } }, update: {}, create: { name: "Alpha Tirna VIII-c", systemId: systemMap[14] } }); planetMap[47] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Hyla VII-a", systemId: systemMap[12] } }, update: {}, create: { name: "Hyla VII-a", systemId: systemMap[12] } }); planetMap[48] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Hyla V-a", systemId: systemMap[12] } }, update: {}, create: { name: "Hyla V-a", systemId: systemMap[12] } }); planetMap[49] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Hyla I-a", systemId: systemMap[12] } }, update: {}, create: { name: "Hyla I-a", systemId: systemMap[12] } }); planetMap[50] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Hyla VIII-b", systemId: systemMap[12] } }, update: {}, create: { name: "Hyla VIII-b", systemId: systemMap[12] } }); planetMap[51] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Hyla VIII-d", systemId: systemMap[12] } }, update: {}, create: { name: "Hyla VIII-d", systemId: systemMap[12] } }); planetMap[52] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Bohr II", systemId: systemMap[5] } }, update: {}, create: { name: "Bohr II", systemId: systemMap[5] } }); planetMap[53] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Bohr III-a", systemId: systemMap[5] } }, update: {}, create: { name: "Bohr III-a", systemId: systemMap[5] } }); planetMap[54] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Bohr IV", systemId: systemMap[5] } }, update: {}, create: { name: "Bohr IV", systemId: systemMap[5] } }); planetMap[55] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Codos", systemId: systemMap[2] } }, update: {}, create: { name: "Codos", systemId: systemMap[2] } }); planetMap[56] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Decaran VII-b", systemId: systemMap[13] } }, update: {}, create: { name: "Decaran VII-b", systemId: systemMap[13] } }); planetMap[57] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Verne I", systemId: systemMap[19] } }, update: {}, create: { name: "Verne I", systemId: systemMap[19] } }); planetMap[58] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Fermi VII-a", systemId: systemMap[7] } }, update: {}, create: { name: "Fermi VII-a", systemId: systemMap[7] } }); planetMap[59] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Huygens VII-c", systemId: systemMap[4] } }, update: {}, create: { name: "Huygens VII-c", systemId: systemMap[4] } }); planetMap[60] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Carinae III-a", systemId: systemMap[9] } }, update: {}, create: { name: "Carinae III-a", systemId: systemMap[9] } }); planetMap[61] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Carinae V-c", systemId: systemMap[9] } }, update: {}, create: { name: "Carinae V-c", systemId: systemMap[9] } }); planetMap[62] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Katydid III", systemId: systemMap[17] } }, update: {}, create: { name: "Katydid III", systemId: systemMap[17] } }); planetMap[63] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Schrodinger II", systemId: systemMap[8] } }, update: {}, create: { name: "Schrodinger II", systemId: systemMap[8] } }); planetMap[64] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Eridani II", systemId: systemMap[11] } }, update: {}, create: { name: "Eridani II", systemId: systemMap[11] } }); planetMap[65] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Shoza VIII-b", systemId: systemMap[21] } }, update: {}, create: { name: "Shoza VIII-b", systemId: systemMap[21] } }); planetMap[66] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Hyla VIII-a", systemId: systemMap[12] } }, update: {}, create: { name: "Hyla VIII-a", systemId: systemMap[12] } }); planetMap[67] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Smet", systemId: systemMap[2] } }, update: {}, create: { name: "Smet", systemId: systemMap[2] } }); planetMap[68] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Nikola II-a", systemId: systemMap[3] } }, update: {}, create: { name: "Nikola II-a", systemId: systemMap[3] } }); planetMap[69] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Zeta Ophiuchi III-a", systemId: systemMap[18] } }, update: {}, create: { name: "Zeta Ophiuchi III-a", systemId: systemMap[18] } }); planetMap[70] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid III", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid III", systemId: systemMap[31] } }); planetMap[71] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid I", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid I", systemId: systemMap[31] } }); planetMap[72] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid I-a", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid I-a", systemId: systemMap[31] } }); planetMap[73] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid I-b", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid I-b", systemId: systemMap[31] } }); planetMap[74] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid II", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid II", systemId: systemMap[31] } }); planetMap[75] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid II-a", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid II-a", systemId: systemMap[31] } }); planetMap[76] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid III-a", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid III-a", systemId: systemMap[31] } }); planetMap[77] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid III-b", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid III-b", systemId: systemMap[31] } }); planetMap[78] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid III-c", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid III-c", systemId: systemMap[31] } }); planetMap[79] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid IV", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid IV", systemId: systemMap[31] } }); planetMap[80] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid V", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid V", systemId: systemMap[31] } }); planetMap[81] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid V-a", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid V-a", systemId: systemMap[31] } }); planetMap[82] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid V-b", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid V-b", systemId: systemMap[31] } }); planetMap[83] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid V-c", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid V-c", systemId: systemMap[31] } }); planetMap[84] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid V-d", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid V-d", systemId: systemMap[31] } }); planetMap[85] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid VI-a", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid VI-a", systemId: systemMap[31] } }); planetMap[86] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid VI", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid VI", systemId: systemMap[31] } }); planetMap[87] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid VI-b", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid VI-b", systemId: systemMap[31] } }); planetMap[88] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid VI-c", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid VI-c", systemId: systemMap[31] } }); planetMap[89] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid VI-d", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid VI-d", systemId: systemMap[31] } }); planetMap[90] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid VII", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid VII", systemId: systemMap[31] } }); planetMap[91] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid VII-a", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid VII-a", systemId: systemMap[31] } }); planetMap[92] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid VII-b", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid VII-b", systemId: systemMap[31] } }); planetMap[93] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid VII-c", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid VII-c", systemId: systemMap[31] } }); planetMap[94] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid VIII", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid VIII", systemId: systemMap[31] } }); planetMap[95] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid VIII-a", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid VIII-a", systemId: systemMap[31] } }); planetMap[96] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid VIII-b", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid VIII-b", systemId: systemMap[31] } }); planetMap[97] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid VIII-c", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid VIII-c", systemId: systemMap[31] } }); planetMap[98] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Muphrid VIII-d", systemId: systemMap[31] } }, update: {}, create: { name: "Muphrid VIII-d", systemId: systemMap[31] } }); planetMap[99] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Schrodinger VIII-b", systemId: systemMap[8] } }, update: {}, create: { name: "Schrodinger VIII-b", systemId: systemMap[8] } }); planetMap[100] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Huygens VII-a", systemId: systemMap[4] } }, update: {}, create: { name: "Huygens VII-a", systemId: systemMap[4] } }); planetMap[101] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Huygens I", systemId: systemMap[4] } }, update: {}, create: { name: "Huygens I", systemId: systemMap[4] } }); planetMap[102] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Carinae I", systemId: systemMap[9] } }, update: {}, create: { name: "Carinae I", systemId: systemMap[9] } }); planetMap[103] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Katydid I-a", systemId: systemMap[17] } }, update: {}, create: { name: "Katydid I-a", systemId: systemMap[17] } }); planetMap[104] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Schrodinger VIII-e", systemId: systemMap[8] } }, update: {}, create: { name: "Schrodinger VIII-e", systemId: systemMap[8] } }); planetMap[105] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Schrodinger I-a", systemId: systemMap[8] } }, update: {}, create: { name: "Schrodinger I-a", systemId: systemMap[8] } }); planetMap[106] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Shoza VIII-d", systemId: systemMap[21] } }, update: {}, create: { name: "Shoza VIII-d", systemId: systemMap[21] } }); planetMap[107] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Shoza V", systemId: systemMap[21] } }, update: {}, create: { name: "Shoza V", systemId: systemMap[21] } }); planetMap[108] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Shoza III-a", systemId: systemMap[21] } }, update: {}, create: { name: "Shoza III-a", systemId: systemMap[21] } }); planetMap[109] = p.id }
  { const p = await prisma.sfPlanet.upsert({ where: { name_systemId: { name: "Decaran II", systemId: systemMap[13] } }, update: {}, create: { name: "Decaran II", systemId: systemMap[13] } }); planetMap[110] = p.id }

  // Facilities
  const facilityMap: Record<number, string> = {}
  { const fac = await prisma.sfFacility.upsert({ where: { abbreviation: "C" }, update: {}, create: { name: "Central Manufacturing Hub", abbreviation: "C", planetId: planetMap[1] } }); facilityMap[1] = fac.id }
  { const fac = await prisma.sfFacility.upsert({ where: { abbreviation: "E" }, update: {}, create: { name: "East Manufacturing Hub", abbreviation: "E", planetId: planetMap[27] } }); facilityMap[2] = fac.id }
  { const fac = await prisma.sfFacility.upsert({ where: { abbreviation: "P" }, update: {}, create: { name: "Central Pharmaceutical Hub", abbreviation: "P", planetId: planetMap[1] } }); facilityMap[3] = fac.id }
  { const fac = await prisma.sfFacility.upsert({ where: { abbreviation: "R" }, update: {}, create: { name: "Robot Manufacturing Hub", abbreviation: "R", planetId: planetMap[3] } }); facilityMap[4] = fac.id }
  { const fac = await prisma.sfFacility.upsert({ where: { abbreviation: "A" }, update: {}, create: { name: "Auxiliary Manufacturing Hub", abbreviation: "A", planetId: planetMap[71] } }); facilityMap[5] = fac.id }
  { const fac = await prisma.sfFacility.upsert({ where: { abbreviation: "V" }, update: {}, create: { name: "Reactor Manufacturing Hub", abbreviation: "V", planetId: planetMap[73] } }); facilityMap[6] = fac.id }

  // Facility Resources
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[18], planetId: planetMap[1] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[18], planetId: planetMap[1], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[47], planetId: planetMap[1] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[47], planetId: planetMap[1], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[35], planetId: planetMap[2] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[35], planetId: planetMap[2], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[4], planetId: planetMap[3] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[4], planetId: planetMap[3], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[19], planetId: planetMap[12] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[19], planetId: planetMap[12], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[3], planetId: planetMap[2] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[3], planetId: planetMap[2], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[12], planetId: planetMap[3] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[12], planetId: planetMap[3], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[75], planetId: planetMap[2] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[75], planetId: planetMap[2], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[58], planetId: planetMap[1] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[58], planetId: planetMap[1], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[65], planetId: planetMap[12] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[65], planetId: planetMap[12], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[26], planetId: planetMap[7] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[26], planetId: planetMap[7], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[13], planetId: planetMap[46] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[13], planetId: planetMap[46], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[21], planetId: planetMap[47] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[21], planetId: planetMap[47], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[38], planetId: planetMap[47] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[38], planetId: planetMap[47], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[68], planetId: planetMap[47] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[68], planetId: planetMap[47], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[40], planetId: planetMap[65] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[40], planetId: planetMap[65], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[69], planetId: planetMap[49] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[69], planetId: planetMap[49], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[59], planetId: planetMap[56] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[59], planetId: planetMap[56], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[44], planetId: planetMap[50] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[44], planetId: planetMap[50], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[8], planetId: planetMap[55] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[8], planetId: planetMap[55], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[70], planetId: planetMap[49] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[70], planetId: planetMap[49], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[2], planetId: planetMap[64] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[2], planetId: planetMap[64], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[14], planetId: planetMap[51] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[14], planetId: planetMap[51], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[32], planetId: planetMap[63] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[32], planetId: planetMap[63], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[37], planetId: planetMap[48] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[37], planetId: planetMap[48], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[22], planetId: planetMap[54] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[22], planetId: planetMap[54], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[50], planetId: planetMap[62] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[50], planetId: planetMap[62], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[55], planetId: planetMap[61] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[55], planetId: planetMap[61], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[41], planetId: planetMap[59] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[41], planetId: planetMap[59], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[64], planetId: planetMap[60] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[64], planetId: planetMap[60], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[71], planetId: planetMap[58] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[71], planetId: planetMap[58], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[53], planetId: planetMap[52] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[53], planetId: planetMap[52], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[72], planetId: planetMap[57] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[72], planetId: planetMap[57], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[1], planetId: planetMap[53] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[1], planetId: planetMap[53], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[54], planetId: planetMap[66] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[54], planetId: planetMap[66], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[63], planetId: planetMap[47] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[63], planetId: planetMap[47], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[33], planetId: planetMap[67] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[33], planetId: planetMap[67], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[1], resourceId: resourceMap[79], planetId: planetMap[1] } }, update: {}, create: { facilityId: facilityMap[1], resourceId: resourceMap[79], planetId: planetMap[1], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[4], resourceId: resourceMap[35], planetId: planetMap[2] } }, update: {}, create: { facilityId: facilityMap[4], resourceId: resourceMap[35], planetId: planetMap[2], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[4], resourceId: resourceMap[19], planetId: planetMap[12] } }, update: {}, create: { facilityId: facilityMap[4], resourceId: resourceMap[19], planetId: planetMap[12], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[4], resourceId: resourceMap[66], planetId: planetMap[68] } }, update: {}, create: { facilityId: facilityMap[4], resourceId: resourceMap[66], planetId: planetMap[68], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[4], resourceId: resourceMap[58], planetId: planetMap[1] } }, update: {}, create: { facilityId: facilityMap[4], resourceId: resourceMap[58], planetId: planetMap[1], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[4], resourceId: resourceMap[78], planetId: planetMap[1] } }, update: {}, create: { facilityId: facilityMap[4], resourceId: resourceMap[78], planetId: planetMap[1], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[4], resourceId: resourceMap[80], planetId: planetMap[12] } }, update: {}, create: { facilityId: facilityMap[4], resourceId: resourceMap[80], planetId: planetMap[12], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[4], resourceId: resourceMap[26], planetId: planetMap[7] } }, update: {}, create: { facilityId: facilityMap[4], resourceId: resourceMap[26], planetId: planetMap[7], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[4], resourceId: resourceMap[44], planetId: planetMap[9] } }, update: {}, create: { facilityId: facilityMap[4], resourceId: resourceMap[44], planetId: planetMap[9], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[4], resourceId: resourceMap[37], planetId: planetMap[16] } }, update: {}, create: { facilityId: facilityMap[4], resourceId: resourceMap[37], planetId: planetMap[16], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[4], resourceId: resourceMap[8], planetId: planetMap[15] } }, update: {}, create: { facilityId: facilityMap[4], resourceId: resourceMap[8], planetId: planetMap[15], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[4], resourceId: resourceMap[53], planetId: planetMap[69] } }, update: {}, create: { facilityId: facilityMap[4], resourceId: resourceMap[53], planetId: planetMap[69], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[4], resourceId: resourceMap[22], planetId: planetMap[68] } }, update: {}, create: { facilityId: facilityMap[4], resourceId: resourceMap[22], planetId: planetMap[68], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[4], resourceId: resourceMap[70], planetId: planetMap[68] } }, update: {}, create: { facilityId: facilityMap[4], resourceId: resourceMap[70], planetId: planetMap[68], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[4], resourceId: resourceMap[69], planetId: planetMap[68] } }, update: {}, create: { facilityId: facilityMap[4], resourceId: resourceMap[69], planetId: planetMap[68], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[4], resourceId: resourceMap[54], planetId: planetMap[70] } }, update: {}, create: { facilityId: facilityMap[4], resourceId: resourceMap[54], planetId: planetMap[70], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[4], resourceId: resourceMap[4], planetId: planetMap[3] } }, update: {}, create: { facilityId: facilityMap[4], resourceId: resourceMap[4], planetId: planetMap[3], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[4], resourceId: resourceMap[12], planetId: planetMap[3] } }, update: {}, create: { facilityId: facilityMap[4], resourceId: resourceMap[12], planetId: planetMap[3], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[4], resourceId: resourceMap[86], planetId: planetMap[3] } }, update: {}, create: { facilityId: facilityMap[4], resourceId: resourceMap[86], planetId: planetMap[3], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[4], resourceId: resourceMap[84], planetId: planetMap[3] } }, update: {}, create: { facilityId: facilityMap[4], resourceId: resourceMap[84], planetId: planetMap[3], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[4], resourceId: resourceMap[82], planetId: planetMap[3] } }, update: {}, create: { facilityId: facilityMap[4], resourceId: resourceMap[82], planetId: planetMap[3], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[4], resourceId: resourceMap[83], planetId: planetMap[3] } }, update: {}, create: { facilityId: facilityMap[4], resourceId: resourceMap[83], planetId: planetMap[3], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[4], resourceId: resourceMap[79], planetId: planetMap[3] } }, update: {}, create: { facilityId: facilityMap[4], resourceId: resourceMap[79], planetId: planetMap[3], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[4], resourceId: resourceMap[85], planetId: planetMap[3] } }, update: {}, create: { facilityId: facilityMap[4], resourceId: resourceMap[85], planetId: planetMap[3], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[4], resourceId: resourceMap[77], planetId: planetMap[3] } }, update: {}, create: { facilityId: facilityMap[4], resourceId: resourceMap[77], planetId: planetMap[3], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[5], resourceId: resourceMap[4], planetId: planetMap[76] } }, update: {}, create: { facilityId: facilityMap[5], resourceId: resourceMap[4], planetId: planetMap[76], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[5], resourceId: resourceMap[12], planetId: planetMap[76] } }, update: {}, create: { facilityId: facilityMap[5], resourceId: resourceMap[12], planetId: planetMap[76], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[5], resourceId: resourceMap[35], planetId: planetMap[71] } }, update: {}, create: { facilityId: facilityMap[5], resourceId: resourceMap[35], planetId: planetMap[71], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[5], resourceId: resourceMap[79], planetId: planetMap[71] } }, update: {}, create: { facilityId: facilityMap[5], resourceId: resourceMap[79], planetId: planetMap[71], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[5], resourceId: resourceMap[47], planetId: planetMap[84] } }, update: {}, create: { facilityId: facilityMap[5], resourceId: resourceMap[47], planetId: planetMap[84], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[5], resourceId: resourceMap[18], planetId: planetMap[84] } }, update: {}, create: { facilityId: facilityMap[5], resourceId: resourceMap[18], planetId: planetMap[84], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[5], resourceId: resourceMap[87], planetId: planetMap[71] } }, update: {}, create: { facilityId: facilityMap[5], resourceId: resourceMap[87], planetId: planetMap[71], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[5], resourceId: resourceMap[89], planetId: planetMap[71] } }, update: {}, create: { facilityId: facilityMap[5], resourceId: resourceMap[89], planetId: planetMap[71], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[5], resourceId: resourceMap[78], planetId: planetMap[71] } }, update: {}, create: { facilityId: facilityMap[5], resourceId: resourceMap[78], planetId: planetMap[71], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[5], resourceId: resourceMap[80], planetId: planetMap[71] } }, update: {}, create: { facilityId: facilityMap[5], resourceId: resourceMap[80], planetId: planetMap[71], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[5], resourceId: resourceMap[90], planetId: planetMap[71] } }, update: {}, create: { facilityId: facilityMap[5], resourceId: resourceMap[90], planetId: planetMap[71], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[5], resourceId: resourceMap[91], planetId: planetMap[71] } }, update: {}, create: { facilityId: facilityMap[5], resourceId: resourceMap[91], planetId: planetMap[71], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[5], resourceId: resourceMap[88], planetId: planetMap[71] } }, update: {}, create: { facilityId: facilityMap[5], resourceId: resourceMap[88], planetId: planetMap[71], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[5], resourceId: resourceMap[83], planetId: planetMap[71] } }, update: {}, create: { facilityId: facilityMap[5], resourceId: resourceMap[83], planetId: planetMap[71], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[5], resourceId: resourceMap[77], planetId: planetMap[71] } }, update: {}, create: { facilityId: facilityMap[5], resourceId: resourceMap[77], planetId: planetMap[71], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[5], resourceId: resourceMap[36], planetId: planetMap[96] } }, update: {}, create: { facilityId: facilityMap[5], resourceId: resourceMap[36], planetId: planetMap[96], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[5], resourceId: resourceMap[58], planetId: planetMap[96] } }, update: {}, create: { facilityId: facilityMap[5], resourceId: resourceMap[58], planetId: planetMap[96], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[5], resourceId: resourceMap[33], planetId: planetMap[94] } }, update: {}, create: { facilityId: facilityMap[5], resourceId: resourceMap[33], planetId: planetMap[94], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[5], resourceId: resourceMap[19], planetId: planetMap[94] } }, update: {}, create: { facilityId: facilityMap[5], resourceId: resourceMap[19], planetId: planetMap[94], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[5], resourceId: resourceMap[65], planetId: planetMap[100] } }, update: {}, create: { facilityId: facilityMap[5], resourceId: resourceMap[65], planetId: planetMap[100], onsite: false, relayId: planetMap[106] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[37], planetId: planetMap[80] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[37], planetId: planetMap[80], onsite: false, subfacility1Id: planetMap[97] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[69], planetId: planetMap[96] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[69], planetId: planetMap[96], onsite: false, subfacility1Id: planetMap[97] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[85], planetId: planetMap[93] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[85], planetId: planetMap[93], onsite: false, subfacility1Id: planetMap[97] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[92], planetId: planetMap[93] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[92], planetId: planetMap[93], onsite: false, subfacility1Id: planetMap[97] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[80], planetId: planetMap[94] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[80], planetId: planetMap[94], onsite: false, subfacility1Id: planetMap[97] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[87], planetId: planetMap[84] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[87], planetId: planetMap[84], onsite: false, subfacility1Id: planetMap[97] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[59], planetId: planetMap[56] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[59], planetId: planetMap[56], onsite: false, subfacility1Id: planetMap[97], relayId: planetMap[68] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[55], planetId: planetMap[61] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[55], planetId: planetMap[61], onsite: false, subfacility1Id: planetMap[97], relayId: planetMap[103] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[64], planetId: planetMap[101] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[64], planetId: planetMap[101], onsite: false, relayId: planetMap[102] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[32], planetId: planetMap[63] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[32], planetId: planetMap[63], onsite: false, subfacility1Id: planetMap[97], relayId: planetMap[104] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[21], planetId: planetMap[105] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[21], planetId: planetMap[105], onsite: false, subfacility1Id: planetMap[97], relayId: planetMap[106] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[96], planetId: planetMap[97] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[96], planetId: planetMap[97], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[94], planetId: planetMap[97] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[94], planetId: planetMap[97], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[93], planetId: planetMap[97] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[93], planetId: planetMap[97], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[95], planetId: planetMap[97] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[95], planetId: planetMap[97], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[78], planetId: planetMap[84] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[78], planetId: planetMap[84], onsite: false, subfacility1Id: planetMap[97], subfacility2Id: planetMap[93] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[80], planetId: planetMap[94] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[80], planetId: planetMap[94], onsite: false, subfacility1Id: planetMap[97], subfacility2Id: planetMap[93] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[83], planetId: planetMap[75] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[83], planetId: planetMap[75], onsite: false, subfacility1Id: planetMap[97], subfacility2Id: planetMap[93] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[77], planetId: planetMap[75] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[77], planetId: planetMap[75], onsite: false, subfacility1Id: planetMap[97], subfacility2Id: planetMap[93] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[70], planetId: planetMap[96] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[70], planetId: planetMap[96], onsite: false, subfacility1Id: planetMap[97], subfacility2Id: planetMap[93] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[44], planetId: planetMap[74] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[44], planetId: planetMap[74], onsite: false, subfacility1Id: planetMap[97], subfacility2Id: planetMap[93] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[26], planetId: planetMap[66] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[26], planetId: planetMap[66], onsite: false, subfacility1Id: planetMap[97], subfacility2Id: planetMap[93], relayId: planetMap[109] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[4], planetId: planetMap[74] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[4], planetId: planetMap[74], onsite: false, subfacility1Id: planetMap[97], subfacility2Id: planetMap[93], subfacility3Id: planetMap[75] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[12], planetId: planetMap[76] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[12], planetId: planetMap[76], onsite: false, subfacility1Id: planetMap[97], subfacility2Id: planetMap[93], subfacility3Id: planetMap[75] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[58], planetId: planetMap[96] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[58], planetId: planetMap[96], onsite: false, subfacility1Id: planetMap[97], subfacility2Id: planetMap[93], subfacility3Id: planetMap[75] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[33], planetId: planetMap[94] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[33], planetId: planetMap[94], onsite: true, subfacility1Id: planetMap[97], subfacility2Id: planetMap[93], subfacility3Id: planetMap[94] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[65], planetId: planetMap[100] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[65], planetId: planetMap[100], onsite: false, subfacility1Id: planetMap[97], subfacility2Id: planetMap[93], subfacility3Id: planetMap[94], relayId: planetMap[106] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[19], planetId: planetMap[75] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[19], planetId: planetMap[75], onsite: true, subfacility1Id: planetMap[97], subfacility2Id: planetMap[93], subfacility3Id: planetMap[75] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[8], planetId: planetMap[93] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[8], planetId: planetMap[93], onsite: true, subfacility1Id: planetMap[97], subfacility2Id: planetMap[93] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[14], planetId: planetMap[97] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[14], planetId: planetMap[97], onsite: true, subfacility1Id: planetMap[97] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[4], planetId: planetMap[74] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[4], planetId: planetMap[74], onsite: false, subfacility1Id: planetMap[97], subfacility2Id: planetMap[93], subfacility3Id: planetMap[84] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[35], planetId: planetMap[77] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[35], planetId: planetMap[77], onsite: false, subfacility1Id: planetMap[97], subfacility2Id: planetMap[93], subfacility3Id: planetMap[84] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[18], planetId: planetMap[84] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[18], planetId: planetMap[84], onsite: true, subfacility1Id: planetMap[97], subfacility2Id: planetMap[93], subfacility3Id: planetMap[84] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[47], planetId: planetMap[84] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[47], planetId: planetMap[84], onsite: true, subfacility1Id: planetMap[97], subfacility2Id: planetMap[93], subfacility3Id: planetMap[84] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[88], planetId: planetMap[75] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[88], planetId: planetMap[75], onsite: false, subfacility1Id: planetMap[97], subfacility2Id: planetMap[93], subfacility3Id: planetMap[84] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[84], planetId: planetMap[97] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[84], planetId: planetMap[97], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[54], planetId: planetMap[108] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[54], planetId: planetMap[108], onsite: false, relayId: planetMap[109] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[50], planetId: planetMap[107] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[50], planetId: planetMap[107], onsite: false, relayId: planetMap[109] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[82], planetId: planetMap[97] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[82], planetId: planetMap[97], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[99], planetId: planetMap[73] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[99], planetId: planetMap[73], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[98], planetId: planetMap[73] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[98], planetId: planetMap[73], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[97], planetId: planetMap[73] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[97], planetId: planetMap[73], onsite: true } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[36], planetId: planetMap[96] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[36], planetId: planetMap[96], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[79], planetId: planetMap[84] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[79], planetId: planetMap[84], onsite: false } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[72], planetId: planetMap[57] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[72], planetId: planetMap[57], onsite: false, relayId: planetMap[110] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[6], resourceId: resourceMap[53], planetId: planetMap[64] } }, update: {}, create: { facilityId: facilityMap[6], resourceId: resourceMap[53], planetId: planetMap[64], onsite: false, relayId: planetMap[106] } })
  await prisma.sfFacilityResource.upsert({ where: { facilityId_resourceId_planetId: { facilityId: facilityMap[5], resourceId: resourceMap[3], planetId: planetMap[71] } }, update: {}, create: { facilityId: facilityMap[5], resourceId: resourceMap[3], planetId: planetMap[71], onsite: true } })

  console.log('Starfield seed complete!')
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())