export const CAIRN_TERMS = {
  outpost: 'The Outpost',
  basecamp: 'Basecamp',
  signals: 'Signals',
  wayfarers: 'Wayfarers',
  waymark: 'Waymark',
  waypoints: 'Waypoints',
  logs: 'Logs',
  logbook: 'Logbook',
  provisions: 'Provisions',
  burn: 'Burn',
  supplylines: 'Supplylines',
  cache: 'Cache',
  trails: 'Trails',
  markers: 'Markers',
  manifest: 'Manifest',
  origins: 'Origins',
  expeditions: 'Expeditions',
  training: 'Training',
  gear: 'Gear',
  landmarks: 'Landmarks',
  summits: 'Summits',
  pathfinding: 'Pathfinding',
  summary: 'Summary',
  headline: 'Headline',
  location: 'Location',
  bio: 'Field Notes',
  bio_button: 'My Journey',
  companions: 'Companions',
  summit_reached: 'Summit Reached',
  explore: 'Explore',
  itinerary: 'Itinerary',
  stops: 'Stops',
  legs: 'Legs',
  on_the_trail: 'On the Trail',
  footprints: 'Footprints',
  guides: 'Guides',
  guide: 'Guide',
  stones: 'Stones',
  stone: 'Stone',
  stoneFace: 'Stone Face',
  stoneCore: 'Stone Core',
  guidePass: 'Guide Pass',
  guideTraverse: 'Guide Traverse',
  scatter: 'Scatter',
  unplaced: 'Unplaced',
  placed: 'Placed',
  setStone: 'Set',
  seated: 'Seated',
}

export const STANDARD_TERMS = {
  outpost: 'Directory',
  basecamp: 'Dashboard',
  signals: 'Messages',
  wayfarers: 'Users',
  waymark: 'Profile',
  waypoints: 'Bookmarks',
  logs: 'Notes',
  logbook: 'Notebook',
  provisions: 'Finance',
  burn: 'Expenses',
  supplylines: 'Subscriptions',
  cache: 'Budgets',
  trails: 'Folders',
  markers: 'Tags',
  manifest: 'Resume',
  origins: 'About',
  expeditions: 'Work Experience',
  training: 'Education',
  gear: 'Skills',
  landmarks: 'Projects',
  summits: 'Achievements',
  pathfinding: 'Volunteering',
  summary: 'Summary',
  headline: 'Title',
  location: 'Location',
  bio: 'Bio',
  bio_button: 'More About Me',
  companions: 'Pets',
  summit_reached: 'In Memoriam',
  explore: 'Search',
  itinerary: 'Calendar',
  stops: 'Events',
  legs: 'Days',
  on_the_trail: 'Upcoming Events',
  footprints: 'Past Events',
  guides: 'Flashcard Decks',
  guide: 'Flashcard Deck',
  stones: 'Flashcards',
  stone: 'Flashcard',
  stoneFace: 'Prompt',
  stoneCore: 'Response',
  guidePass: 'Deck Run-through',
  guideTraverse: 'Multi-deck Run-through',
  scatter: 'Shuffle',
  unplaced: 'Unseen',
  placed: 'Still Learning',
  setStone: 'Reinforced',
  seated: 'Mastered',
}

export type Terms = typeof CAIRN_TERMS
export type TerminologyStyle = 'CAIRN' | 'STANDARD'

export function getTerms(style: TerminologyStyle): Terms {
  return style === 'CAIRN' ? CAIRN_TERMS : STANDARD_TERMS
}